// Mock data — 6 Indian demo businesses

const BUSINESSES = {
   baker: {
     id: 'baker',
     name: "Priya's Bakes",
     category: 'Home Baker',
     location: 'Pune, Maharashtra',
    initials: 'PB',
    color: '#a16207',
    owner: 'Priya',
    peakHours: [
      [5,  10, 25, 38, 30, 20, 14, 10,  7,  5,  3,  2],
      [5,  12, 28, 40, 32, 22, 16, 12,  9,  6,  4,  2],
      [6,  14, 30, 42, 34, 24, 18, 13, 10,  7,  5,  3],
      [8,  18, 35, 46, 38, 28, 20, 16, 13, 10,  6,  4],
      [12, 26, 48, 58, 50, 36, 26, 20, 18, 16, 12,  8],
      [32, 62, 82, 90, 80, 66, 52, 42, 30, 22, 14,  8],
      [22, 50, 70, 76, 66, 52, 38, 28, 20, 14,  9,  5],
    ],
    metrics: {
      revenue:   { value: 94800,  delta: 8.2,  label: 'Revenue',          unit: '₹', period: 'this month' },
      orders:    { value: 246,    delta: 12.4, label: 'Orders',            period: 'this month' },
      conversion:{ value: 4.2,   delta: -0.3, label: 'Conversion',        unit: '%', period: 'website' },
      inventory: { value: 87,    delta: 2.1,  label: 'Inventory health',  unit: '%' },
      retention: { value: 68,    delta: 5.0,  label: 'Repeat customers',  unit: '%' },
      sentiment: { value: 4.7,   delta: 0.1,  label: 'Review sentiment',  unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 128000 }, { m: 'Dec', v: 104000 }, { m: 'Jan', v: 68000 },
      { m: 'Feb', v: 74000  }, { m: 'Mar', v: 86000  }, { m: 'Apr', v: 89000 },
      { m: 'May', v: 94800  },
    ],
    ordersSeries: [
      { d: 'Mon', v: 28 }, { d: 'Tue', v: 32 }, { d: 'Wed', v: 36 },
      { d: 'Thu', v: 30 }, { d: 'Fri', v: 48 }, { d: 'Sat', v: 58 }, { d: 'Sun', v: 42 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 180 }, { m: 'Dec', v: 210 }, { m: 'Jan', v: 234 },
      { m: 'Feb', v: 258 }, { m: 'Mar', v: 284 }, { m: 'Apr', v: 318 }, { m: 'May', v: 352 },
    ],
    topMovers: [
      ['Chocolate truffle cake', 284, 22],
      ['Ladoo box (12 pc)',       192, 48],
      ['Eggless brownie',         168, 14],
      ['Custom birthday cake',     28, -8],
      ['Cookie hamper',           112, 16],
    ],
    insights: [
      {
        title: 'Diwali orders 3x normal — pre-booking window opens in 8 weeks',
        body: 'November revenue hit ₹1.28L on gift hamper orders. WhatsApp enquiries started 6 weeks before. Starting pre-booking slots in July with ₹500 advance locks demand early.',
        evidence: ['Order history', 'Seasonal pattern'],
        severity: 'positive',
      },
      {
        title: 'Custom cake margin at 48% — highest in your menu',
        body: 'Custom celebration cakes average ₹2,400 and take similar effort as a ₹280 cookie box. Shifting 4 more orders per week to custom cakes would add ₹38,400 per month.',
        evidence: ['Order mix', 'COGS log'],
        severity: 'info',
      },
      {
        title: 'Maida and butter costs up 18% since February',
        body: 'Input costs rose after the recent commodity price hike. Menu pricing was set in Q4 2025. Eggless cake margin has dropped from 42% to 34%.',
        evidence: ['COGS log', 'Supplier invoices'],
        severity: 'warning',
      },
    ],
    actions: [
      {
        title: 'Launch Diwali pre-booking on WhatsApp in July',
        body: 'Message your 94 repeat customers with a ₹500 advance deposit option. Last Diwali: 38 orders. Target 60 this year. Projected: +₹52,000.',
        impact: '+₹52,000',
        effort: 'Low',
        confidence: 88,
      },
      {
        title: 'Raise eggless cake price by ₹80',
        body: 'Restores pre-February margin without exceeding Pune market median. Estimated demand drop under 4% based on recent enquiry volume.',
        impact: '+₹6,400/mo',
        effort: 'Low',
        confidence: 82,
      },
      {
        title: 'Reorder maida and sugar by Thursday',
        body: 'At current bake rate (32 kg/week) you will run short before Saturday rush. Supplier minimum is 25 kg. Order now to avoid weekend stockout.',
        impact: 'Avoid stockout',
        effort: 'Low',
        confidence: 96,
        urgent: true,
      },
    ],
    automations: [
      { id: 'a1', trigger: 'Ingredient stock below 5-day threshold', action: 'Send WhatsApp to supplier for reorder', status: 'active', last: '3 days ago' },
      { id: 'a2', trigger: 'New Google review under 4 stars', action: 'Draft personalised reply for approval', status: 'active', last: '8 days ago' },
      { id: 'a3', trigger: 'Customer last ordered > 30 days ago', action: 'Send "miss you" WhatsApp with seasonal special', status: 'disabled', last: 'never' },
    ],
    suggestedAutomations: [
      { trigger: 'Weekend demand forecast > 65 orders', action: 'Notify Thursday to scale prep batches' },
      { trigger: 'Instagram post with > 300 likes', action: 'Auto-reply with order link and availability' },
    ],
    spendingMix: [
      { label: 'Ingredients', value: 32400, color: '#a16207' },
      { label: 'Packaging',   value: 5800,  color: '#78716c' },
      { label: 'Delivery',    value: 4200,  color: '#1e40af' },
      { label: 'Marketing',   value: 2400,  color: '#15803d' },
      { label: 'Other',       value: 1200,  color: '#d6d3d1' },
    ],
  },

   retail: {
     id: 'retail',
     name: 'Vrindavan Textiles',
     category: 'Retail Shop',
     location: 'Surat, Gujarat',
    initials: 'VT',
    color: '#1e40af',
    owner: 'Rajesh',
    peakHours: [
      [ 4,  8, 22, 38, 36, 28, 24, 30, 38, 44, 32, 18],
      [ 4,  8, 24, 40, 38, 30, 26, 32, 40, 46, 34, 20],
      [ 5, 10, 26, 42, 40, 32, 28, 34, 42, 48, 36, 22],
      [ 6, 12, 28, 44, 42, 34, 30, 36, 44, 50, 38, 24],
      [ 8, 16, 34, 50, 46, 38, 34, 42, 58, 75, 68, 42],
      [15, 30, 58, 72, 66, 56, 50, 56, 64, 60, 46, 28],
      [ 8, 20, 42, 56, 50, 40, 32, 36, 40, 38, 26, 14],
    ],
    metrics: {
      revenue:   { value: 584000, delta: 4.1,  label: 'Revenue',         unit: '₹', period: 'this month' },
      orders:    { value: 1480,   delta: -2.1, label: 'Orders',          period: 'this month' },
      conversion:{ value: 2.8,   delta: 0.4,  label: 'Conversion',      unit: '%' },
      inventory: { value: 72,    delta: -3.0, label: 'Inventory health', unit: '%' },
      retention: { value: 44,    delta: 1.2,  label: 'Repeat customers', unit: '%' },
      sentiment: { value: 4.4,   delta: -0.1, label: 'Review sentiment', unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 780000 }, { m: 'Dec', v: 540000 }, { m: 'Jan', v: 480000 },
      { m: 'Feb', v: 520000 }, { m: 'Mar', v: 560000 }, { m: 'Apr', v: 560000 },
      { m: 'May', v: 584000 },
    ],
    ordersSeries: [
      { d: 'Mon', v: 168 }, { d: 'Tue', v: 192 }, { d: 'Wed', v: 208 },
      { d: 'Thu', v: 224 }, { d: 'Fri', v: 268 }, { d: 'Sat', v: 242 }, { d: 'Sun', v: 156 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 1640 }, { m: 'Dec', v: 1820 }, { m: 'Jan', v: 1880 },
      { m: 'Feb', v: 1960 }, { m: 'Mar', v: 2040 }, { m: 'Apr', v: 2120 }, { m: 'May', v: 2240 },
    ],
    topMovers: [
      ['Silk saree (6 yards)',  284, 18],
      ['Cotton salwar set',     412,  8],
      ['Printed kurti',         368, 24],
      ['Bridal lehenga',          8, -22],
      ['Chanderi dupatta',      128, 12],
    ],
    insights: [
      {
        title: 'Navratri and wedding season — 6 weeks away',
        body: 'Chaniya choli and bridal lehenga orders spike 280% in Sept–Oct in Surat. Last year you ran out of stock by October 2. Early stocking in August protects ₹2.4L in potential festive sales.',
        evidence: ['Sales history', 'Seasonal pattern'],
        severity: 'positive',
      },
      {
        title: 'Polyester stock ageing — 18 SKUs unsold for 60+ days',
        body: 'Holding cost is ₹18,400 per month. Summer buyers prefer cotton. A 20% markdown before monsoon sets in recovers ₹1.1L capital and frees shelf space for festive stock.',
        evidence: ['Inventory age', 'Season data'],
        severity: 'warning',
      },
      {
        title: 'B2B boutique reorders growing',
        body: 'Three Pune boutiques have reordered twice each this quarter. B2B margin is 8% lower but order size is 12x. Average reorder cadence is 22 days.',
        evidence: ['Order source', 'Customer type'],
        severity: 'info',
      },
    ],
    actions: [
      { title: 'Place festive season stock order by 15 July', body: 'Lock in chaniya choli and lehenga fabric before August price increase. ₹80,000 investment, projected ₹2.4L in Navratri revenue.', impact: '+₹2.4L season', effort: 'Med', confidence: 86 },
      { title: 'Markdown 18 polyester SKUs by 20%', body: 'Recovers ₹1.1L capital, frees shelf for festive inventory. Act before monsoon drops foot traffic further.', impact: '+₹1.1L cash', effort: 'Low', confidence: 82 },
      { title: 'Formalise B2B boutique discount program', body: 'Offer 5% volume discount at ₹50,000+ orders. Three boutiques qualify today. Net positive vs walk-in margin on the same stock.', impact: '+₹38,000/mo', effort: 'Low', confidence: 74 },
    ],
    automations: [
      { id: 'a1', trigger: 'SKU on shelf > 60 days', action: 'Flag for markdown review in daily report', status: 'active', last: 'yesterday' },
      { id: 'a2', trigger: 'Daily revenue 20% below forecast', action: 'Draft WhatsApp offer for loyal customers', status: 'disabled', last: 'never' },
      { id: 'a3', trigger: 'New review posted', action: 'Notify and draft reply', status: 'active', last: '2 days ago' },
    ],
    suggestedAutomations: [
      { trigger: 'Inventory below 14-day festive threshold', action: 'Create purchase order draft for approval' },
      { trigger: 'Wedding season starts (15 Sept)', action: 'Activate festive campaign on Instagram and WhatsApp' },
    ],
    spendingMix: [
      { label: 'Fabric stock', value: 280000, color: '#1e40af' },
      { label: 'Rent',         value: 42000,  color: '#a16207' },
      { label: 'Staff',        value: 68000,  color: '#15803d' },
      { label: 'Marketing',    value: 18000,  color: '#78716c' },
      { label: 'Other',        value: 8000,   color: '#d6d3d1' },
    ],
  },

   pharmacy: {
     id: 'pharmacy',
     name: 'Swasthya Medicals',
     category: 'Pharmacy',
     location: 'Ahmedabad, Gujarat',
    initials: 'SM',
    color: '#15803d',
    owner: 'Dr. Anjali',
    peakHours: [
      [20, 72, 88, 80, 68, 58, 44, 36, 28, 22, 14,  8],
      [18, 68, 84, 76, 64, 54, 40, 32, 24, 18, 12,  6],
      [16, 64, 80, 72, 60, 50, 38, 30, 22, 16, 10,  5],
      [14, 60, 76, 68, 56, 46, 34, 28, 20, 14,  9,  4],
      [18, 70, 86, 78, 66, 56, 42, 34, 26, 20, 12,  6],
      [10, 38, 60, 72, 64, 50, 38, 28, 20, 14,  8,  4],
      [ 4, 12, 24, 36, 32, 24, 18, 12,  8,  6,  3,  2],
    ],
    metrics: {
      revenue:   { value: 980000, delta: 2.8, label: 'Revenue',           unit: '₹' },
      orders:    { value: 2840,   delta: 1.4, label: 'Prescriptions filled' },
      conversion:{ value: 91,    delta: 0.6, label: 'Refill rate',        unit: '%' },
      inventory: { value: 94,    delta: 0.8, label: 'Inventory health',   unit: '%' },
      retention: { value: 76,    delta: 0.4, label: 'Repeat customers',   unit: '%' },
      sentiment: { value: 4.6,   delta: 0.0, label: 'Review sentiment',   unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 920000 }, { m: 'Dec', v: 940000 }, { m: 'Jan', v: 920000 },
      { m: 'Feb', v: 940000 }, { m: 'Mar', v: 960000 }, { m: 'Apr', v: 960000 },
      { m: 'May', v: 980000 },
    ],
    ordersSeries: [
      { d: 'Mon', v: 520 }, { d: 'Tue', v: 498 }, { d: 'Wed', v: 484 },
      { d: 'Thu', v: 462 }, { d: 'Fri', v: 528 }, { d: 'Sat', v: 412 }, { d: 'Sun', v: 284 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 2680 }, { m: 'Dec', v: 2720 }, { m: 'Jan', v: 2760 },
      { m: 'Feb', v: 2800 }, { m: 'Mar', v: 2840 }, { m: 'Apr', v: 2880 }, { m: 'May', v: 2940 },
    ],
    topMovers: [
      ['Paracetamol 500mg',     684, 4],
      ['Cetirizine 10mg',       520, 38],
      ['Vitamin D3 sachet',     312, 22],
      ['BP monitor (Omron)',     18, -6],
      ['Cough syrup D-Cold',    248, 14],
    ],
    insights: [
      {
        title: 'Monsoon medicines — demand surge in 6 weeks',
        body: 'ORS, paracetamol, and anti-diarrhoeals spike 60–80% in July–August in Ahmedabad. Last year you ran out of ORS sachets by July 18. Stock up now to protect ₹42,000 in monsoon revenue.',
        evidence: ['Rx history', 'Seasonal pattern'],
        severity: 'positive',
      },
      {
        title: 'Jan Aushadhi generic substitution driving retention',
        body: 'Your generic panel covers 42% of prescription volume. Patients counselled on generics show 94% retention vs 78% for those not aware. Every ₹100 saved builds a repeat customer.',
        evidence: ['Sales mix', 'Retention data'],
        severity: 'info',
      },
      {
        title: 'Tuesday afternoons understaffed — 24-min avg wait',
        body: 'Target is 15 minutes. A technician is on leave Tuesday afternoons. Eight complaints in 30 days cite wait time as the reason for low ratings.',
        evidence: ['Fill timing', 'Complaint log'],
        severity: 'warning',
      },
    ],
    actions: [
      { title: 'Stock 500 ORS + 200 paracetamol strips by June 15', body: "Matches last July's peak demand. Prevents stockout during peak monsoon. Pays back within 3 days of July sales.", impact: 'Prevent ₹42,000 miss', effort: 'Low', confidence: 90 },
      { title: 'Shift 1 technician to Tuesday afternoons', body: 'No extra payroll — swap with Thursday morning. Reduces wait time to ~16 min. Addresses the top complaint driver.', impact: '-8 min avg wait', effort: 'Low', confidence: 86 },
      { title: 'Launch WhatsApp prescription refill service', body: '68% of your regulars are on WhatsApp. Photo of prescription → ready in 30 min. Similar pharmacies report 18% revenue lift after launch.', impact: '+₹18,000/mo', effort: 'Med', confidence: 74 },
    ],
    automations: [
      { id: 'a1', trigger: 'Refill due in 3 days', action: 'Send WhatsApp reminder to patient', status: 'active', last: 'today' },
      { id: 'a2', trigger: 'Schedule H drug below reorder level', action: 'Alert pharmacist and draft reorder', status: 'active', last: '2 weeks ago' },
      { id: 'a3', trigger: 'Negative Google review', action: 'Draft empathetic reply for approval', status: 'disabled', last: 'never' },
    ],
    suggestedAutomations: [
      { trigger: 'Monsoon forecast for Ahmedabad (June 15+)', action: 'Alert team to feature ORS and monsoon pack at counter' },
      { trigger: 'Patient last refill > 45 days', action: 'Send care check-in WhatsApp message' },
    ],
    spendingMix: [
      { label: 'Medicines',  value: 580000, color: '#15803d' },
      { label: 'Staff',      value: 248000, color: '#a16207' },
      { label: 'Rent',       value: 68000,  color: '#1e40af' },
      { label: 'Other',      value: 32000,  color: '#78716c' },
    ],
  },

   cafe: {
     id: 'cafe',
     name: 'Chai Trunk',
     category: 'Cafe',
     location: 'Bengaluru, Karnataka',
    initials: 'CT',
    color: '#7c2d12',
    owner: 'Arjun',
    peakHours: [
      [55, 90, 82, 68, 72, 60, 42, 30, 20, 14,  8,  5],
      [52, 88, 80, 65, 70, 58, 40, 28, 18, 12,  7,  4],
      [58, 92, 84, 70, 74, 62, 44, 32, 22, 16,  9,  5],
      [60, 94, 86, 72, 76, 64, 46, 34, 24, 18, 10,  6],
      [62, 90, 84, 70, 74, 62, 50, 38, 28, 22, 14,  8],
      [38, 72, 80, 76, 68, 58, 50, 44, 38, 30, 22, 14],
      [28, 60, 72, 68, 60, 50, 42, 36, 28, 22, 16,  9],
    ],
    metrics: {
      revenue:   { value: 264000, delta: 6.2, label: 'Revenue',          unit: '₹' },
      orders:    { value: 5840,   delta: 8.1, label: 'Transactions' },
      conversion:{ value: 38,    delta: 1.8, label: 'Loyalty signups',   unit: '%' },
      inventory: { value: 80,    delta: -1.0,label: 'Inventory health',  unit: '%' },
      retention: { value: 62,    delta: 3.2, label: 'Repeat customers',  unit: '%' },
      sentiment: { value: 4.5,   delta: 0.2, label: 'Review sentiment',  unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 224000 }, { m: 'Dec', v: 240000 }, { m: 'Jan', v: 218000 },
      { m: 'Feb', v: 234000 }, { m: 'Mar', v: 248000 }, { m: 'Apr', v: 256000 },
      { m: 'May', v: 264000 },
    ],
    ordersSeries: [
      { d: 'Mon', v: 840 }, { d: 'Tue', v: 812 }, { d: 'Wed', v: 868 },
      { d: 'Thu', v: 892 }, { d: 'Fri', v: 964 }, { d: 'Sat', v: 724 }, { d: 'Sun', v: 588 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 920 }, { m: 'Dec', v: 980 }, { m: 'Jan', v: 1060 },
      { m: 'Feb', v: 1160 }, { m: 'Mar', v: 1280 }, { m: 'Apr', v: 1420 }, { m: 'May', v: 1560 },
    ],
    topMovers: [
      ['Masala chai',      1284, 18],
      ['Filter coffee',     924,  8],
      ['Vada pav',          612, 24],
      ['Samosa (2 pc)',      488, 14],
      ['Cold brew',         224, 56],
    ],
    insights: [
      {
        title: 'Swiggy/Zomato commission eroding ₹28,000 per month',
        body: 'Platform orders are 38% of revenue but margin drops to 12% after the 25% commission cut. Direct counter orders run at 58% margin. Shifting 15% of app orders to direct would save ₹18,000 per month.',
        evidence: ['Channel mix', 'Margin by channel'],
        severity: 'warning',
      },
      {
        title: 'IT park proximity drives 68% of weekday revenue',
        body: 'The tech park 200m away sends ~180 people between 8–10am and 1–2pm. Office holiday calendar shows 3 long weekends in June — prepare for a 40% dip on those days.',
        evidence: ['Customer survey', 'Transaction timing'],
        severity: 'info',
      },
      {
        title: 'Filter coffee upsell working — avg ticket up ₹28',
        body: 'Staff suggesting filter coffee with snacks lifted the average ticket from ₹82 to ₹110 over 3 months. 24% of customers now order the combo.',
        evidence: ['Order mix', 'Staff data'],
        severity: 'positive',
      },
    ],
    actions: [
      { title: 'Add QR + WhatsApp ordering for direct delivery', body: 'Give your top-100 loyalty members a direct ordering link. Remove Swiggy for nearby delivery under 1km. Net: +₹18,000/mo margin recovery.', impact: '+₹18,000/mo', effort: 'Med', confidence: 84 },
      { title: 'Stock cold brew and nimbu pani for June heat', body: 'Bengaluru heat forecast: 36°C+ for 3 weeks. Pre-order cold brew concentrate. Last summer, cold drinks were 40% of June revenue.', impact: '+₹14,000/mo', effort: 'Low', confidence: 80 },
      { title: 'Run "no platform" Tuesday offer — 10% off direct', body: 'Shifts at least 20% of app regulars to direct counter ordering. Low cost, test for 4 weeks, measure margin impact.', impact: 'Test', effort: 'Low', confidence: 68 },
    ],
    automations: [
      { id: 'a1', trigger: 'Loyalty member 14 days inactive', action: 'Send WhatsApp "miss you" chai voucher', status: 'active', last: '2 days ago' },
      { id: 'a2', trigger: 'Daily milk pull > 20 litres', action: 'Add to tomorrow standing order', status: 'active', last: 'today' },
      { id: 'a3', trigger: 'Negative review on Swiggy or Google', action: 'Draft empathetic reply for approval', status: 'active', last: '5 days ago' },
    ],
    suggestedAutomations: [
      { trigger: 'Temperature forecast > 34°C tomorrow', action: 'Promote cold brew and nimbu pani on Instagram story' },
      { trigger: 'Office holiday next day', action: 'Reduce milk order and adjust staff shift' },
    ],
    spendingMix: [
      { label: 'Tea, coffee & dairy', value: 88000, color: '#7c2d12' },
      { label: 'Snacks & food',       value: 32000, color: '#a16207' },
      { label: 'Staff',               value: 72000, color: '#15803d' },
      { label: 'Rent',                value: 36000, color: '#1e40af' },
      { label: 'Other',               value: 8000,  color: '#78716c' },
    ],
  },

   trade: {
     id: 'trade',
     name: 'Bharat Global Exports',
     category: 'Import/Export',
     location: 'Mumbai, Maharashtra',
    initials: 'BG',
    color: '#1e40af',
    owner: 'Vikram',
    peakHours: [
      [2, 12, 55, 72, 68, 80, 76, 64, 58, 42, 22,  8],
      [2, 10, 52, 68, 64, 76, 72, 60, 54, 38, 20,  6],
      [2, 12, 56, 70, 66, 78, 74, 62, 56, 40, 22,  7],
      [2, 14, 60, 74, 70, 82, 78, 66, 60, 44, 24,  8],
      [2, 12, 54, 68, 64, 74, 70, 58, 52, 36, 18,  5],
      [1,  4, 10, 16, 14, 12, 10,  8,  6,  4,  2,  1],
      [1,  2,  4,  6,  5,  4,  3,  2,  2,  1,  1,  1],
    ],
    metrics: {
      revenue:   { value: 3240000, delta: -1.4, label: 'Revenue',            unit: '₹' },
      orders:    { value: 22,      delta: 12.0,  label: 'Shipments' },
      conversion:{ value: 84,     delta: -2.1,  label: 'On-time rate',       unit: '%' },
      inventory: { value: 68,     delta: -4.2,  label: 'Container util.',    unit: '%' },
      retention: { value: 92,     delta: 0.8,   label: 'Client retention',   unit: '%' },
      sentiment: { value: 4.2,    delta: -0.1,  label: 'Client NPS',         unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 3200000 }, { m: 'Dec', v: 3480000 }, { m: 'Jan', v: 3120000 },
      { m: 'Feb', v: 3280000 }, { m: 'Mar', v: 3360000 }, { m: 'Apr', v: 3280000 },
      { m: 'May', v: 3240000 },
    ],
    ordersSeries: [
      { d: 'Mon', v: 6 }, { d: 'Tue', v: 4 }, { d: 'Wed', v: 5 },
      { d: 'Thu', v: 7 }, { d: 'Fri', v: 4 }, { d: 'Sat', v: 1 }, { d: 'Sun', v: 1 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 34 }, { m: 'Dec', v: 36 }, { m: 'Jan', v: 38 },
      { m: 'Feb', v: 40 }, { m: 'Mar', v: 42 }, { m: 'Apr', v: 44 }, { m: 'May', v: 46 },
    ],
    topMovers: [
      ['Printed cotton fabric (bales)', 8, 22],
      ['Handicraft items (cartons)',   12, -4],
      ['Spice export (MT)',             6, 18],
      ['Garment accessories',          14,  8],
      ['Leather goods',                 4, -16],
    ],
    insights: [
      {
        title: 'JNPT congestion adding 5–7 days to May shipments',
        body: 'Dwell time at JNPT averaged 6.2 days in May vs 2.8 in February. Three UAE shipments risk 30-day delivery clause penalties totalling ₹2.8L.',
        evidence: ['Port data', 'Shipment manifest'],
        severity: 'warning',
      },
      {
        title: 'USD/INR at 84.2 — most favourable rate in 18 months',
        body: 'Your last four USD receivables settled at ₹84.2 effective rate. Hedging the next 60-day receivables at current rate locks in ₹6.4L vs the 12-month average.',
        evidence: ['FX log', 'Receivables'],
        severity: 'positive',
      },
      {
        title: 'Dubai client (Al Rashid Trading) ordering cadence dropped',
        body: 'Monthly orders since February; now quarterly. Pattern matches competitive pressure. They represent ₹4.8L per month in revenue — worth a direct call.',
        evidence: ['Client cadence', 'Order history'],
        severity: 'info',
      },
    ],
    actions: [
      { title: 'Pre-clear three May UAE shipments via CHB', body: 'Custom House Broker fast-track costs ₹18,000 but avoids ₹2.8L penalty exposure. File by Wednesday.', impact: 'Avoid ₹2.8L penalty', effort: 'Med', confidence: 88, urgent: true },
      { title: 'Hedge ₹18L receivables at current rate', body: 'Lock in USD 2.14L at ₹84.2. Best rate in 18 months. Forward contract with HDFC trade desk, 60-day tenor.', impact: '+₹6.4L locked', effort: 'Low', confidence: 80 },
      { title: 'Call Al Rashid, offer Q3 commitment discount', body: '3% discount on ₹12L order retains ₹46L per year account. Volume drop signals churn risk — act this week.', impact: 'Retain ₹46L/yr', effort: 'Low', confidence: 72 },
    ],
    automations: [
      { id: 'a1', trigger: 'Shipment ETA delayed > 48 hours', action: 'Notify client and draft revised ETA email', status: 'active', last: 'yesterday' },
      { id: 'a2', trigger: 'USD/INR moves > 1.5% in a day', action: 'Alert ops and draft hedging recommendation', status: 'active', last: '3 weeks ago' },
      { id: 'a3', trigger: 'Client order cadence drops > 30%', action: 'Add to sales follow-up list', status: 'disabled', last: 'never' },
    ],
    suggestedAutomations: [
      { trigger: 'Container booking confirmed at JNPT', action: 'Auto-generate client tracking update with ETA' },
      { trigger: 'GST filing due in 5 days', action: 'Notify accounts team with checklist' },
    ],
    spendingMix: [
      { label: 'Goods',          value: 1960000, color: '#1e40af' },
      { label: 'Logistics',      value: 580000,  color: '#a16207' },
      { label: 'Customs & duties',value: 180000, color: '#15803d' },
      { label: 'Staff',          value: 140000,  color: '#78716c' },
      { label: 'Other',          value: 36000,   color: '#d6d3d1' },
    ],
  },

   service: {
     id: 'service',
     name: 'Skyline Interiors',
     category: 'Service Business',
     location: 'Gurugram, Haryana',
    initials: 'SI',
    color: '#15803d',
    owner: 'Neha',
    peakHours: [
      [2, 18, 58, 72, 74, 68, 62, 70, 66, 48, 22,  6],
      [2, 20, 62, 76, 78, 72, 66, 74, 70, 52, 24,  7],
      [2, 18, 60, 74, 76, 70, 64, 72, 68, 50, 22,  6],
      [2, 22, 66, 80, 82, 76, 70, 78, 74, 56, 26,  8],
      [2, 18, 56, 68, 70, 64, 58, 64, 60, 44, 20,  5],
      [1,  6, 14, 22, 20, 16, 12, 10,  8,  6,  3,  1],
      [1,  2,  3,  4,  3,  3,  2,  2,  1,  1,  1,  1],
    ],
    metrics: {
      revenue:   { value: 496000, delta: 11.8, label: 'Revenue',         unit: '₹' },
      orders:    { value: 11,     delta: 16.0, label: 'Active projects' },
      conversion:{ value: 38,    delta: 4.2,  label: 'Quote close rate', unit: '%' },
      inventory: { value: 91,    delta: 1.4,  label: 'Schedule load',    unit: '%' },
      retention: { value: 72,    delta: 5.4,  label: 'Referral rate',    unit: '%' },
      sentiment: { value: 4.8,   delta: 0.0,  label: 'Review sentiment', unit: '/5' },
    },
    revenueSeries: [
      { m: 'Nov', v: 340000 }, { m: 'Dec', v: 300000 }, { m: 'Jan', v: 280000 },
      { m: 'Feb', v: 380000 }, { m: 'Mar', v: 420000 }, { m: 'Apr', v: 448000 },
      { m: 'May', v: 496000 },
    ],
    ordersSeries: [
      { d: 'Mon', v: 4 }, { d: 'Tue', v: 5 }, { d: 'Wed', v: 5 },
      { d: 'Thu', v: 6 }, { d: 'Fri', v: 4 }, { d: 'Sat', v: 1 }, { d: 'Sun', v: 0 },
    ],
    customerGrowth: [
      { m: 'Nov', v: 78 }, { m: 'Dec', v: 82 }, { m: 'Jan', v: 88 },
      { m: 'Feb', v: 96 }, { m: 'Mar', v: 106 }, { m: 'Apr', v: 118 }, { m: 'May', v: 132 },
    ],
    topMovers: [
      ['Modular kitchen',         4, 22],
      ['Wardrobe fit-out',        6, 18],
      ['Living room renovation',  5,  8],
      ['Master bedroom',          3, -8],
      ['Painting',                8, -24],
    ],
    insights: [
      {
        title: 'Modular kitchen jobs at 38% margin vs 21% for painting',
        body: 'Modular kitchen and wardrobe projects average ₹3.8L at 38% margin. Painting jobs average ₹48,000 at 21%. Kitchen leads take 2x longer to close but contribute 80% of gross profit.',
        evidence: ['Project margins', 'Job mix'],
        severity: 'info',
      },
      {
        title: 'Crew at 91% utilisation — June overrun risk',
        body: 'Four projects overlap in June second week. Without a 5th carpenter, delays are likely. Labour sourcing in Gurugram takes 3 weeks — start now.',
        evidence: ['Crew schedule', 'Project timeline'],
        severity: 'warning',
      },
      {
        title: 'DLF society referrals are your strongest channel',
        body: '72% of May leads came from DLF Phase 3 and 4 residents. MagicBricks ads delivered 3 leads at ₹4,200 CAC — worst channel. Referral close rate is 62% vs 22% for paid.',
        evidence: ['Lead source', 'Close rate'],
        severity: 'positive',
      },
    ],
    actions: [
      { title: 'Raise painting project minimum to ₹60,000', body: 'Filters low-margin jobs. At current mix, adds ₹22,000/mo without losing high-value project leads.', impact: '+₹22,000/mo', effort: 'Low', confidence: 80 },
      { title: 'Hire a 5th carpenter by June 1', body: 'ITI-trained carpenter rate in Gurugram is ₹580/day. Prevents June delays. Net positive at >₹60,000/mo billed work.', impact: 'Capacity for +2 projects', effort: 'Med', confidence: 76 },
      { title: 'Pause MagicBricks, launch DLF referral reward', body: '₹2,000 referral reward beats ₹4,200 MagicBricks CAC by 52%. Close rate 3x better. Test for 60 days.', impact: '+₹12,000/mo', effort: 'Low', confidence: 82 },
    ],
    automations: [
      { id: 'a1', trigger: 'Project marked complete', action: 'Send 1-week follow-up + Google review request', status: 'active', last: '2 days ago' },
      { id: 'a2', trigger: 'Quote sent', action: 'Draft 3-day and 7-day WhatsApp follow-ups', status: 'active', last: 'today' },
      { id: 'a3', trigger: 'New 5-star Google review', action: 'Thank client, request Instagram post with permission', status: 'disabled', last: 'never' },
    ],
    suggestedAutomations: [
      { trigger: 'Crew utilisation > 95% for 7 days', action: 'Alert: slow new project intake or begin hiring' },
      { trigger: 'Post-monsoon season starts (Oct 1)', action: 'Activate Diwali renovation campaign in DLF societies' },
    ],
    spendingMix: [
      { label: 'Materials',      value: 192000, color: '#15803d' },
      { label: 'Labour',         value: 148000, color: '#a16207' },
      { label: 'Subcontractors', value: 58000,  color: '#1e40af' },
      { label: 'Transport',      value: 18000,  color: '#78716c' },
      { label: 'Other',          value: 9000,   color: '#d6d3d1' },
    ],
  },
};

const BUSINESS_LIST = [
  { id: 'baker',    name: "Priya's Bakes",       desc: 'Custom cakes & baked goods, Pune',        icon: 'baker'    },
  { id: 'retail',   name: 'Vrindavan Textiles', desc: 'Textiles & garments, Surat',              icon: 'retail'   },
  { id: 'pharmacy', name: 'Swasthya Medicals',  desc: 'Medical store, Ahmedabad',                icon: 'pharmacy' },
  { id: 'trade',    name: 'Bharat Global Exports', desc: 'Global freight & exports, Mumbai',     icon: 'trade'    },
  { id: 'service',  name: 'Skyline Interiors',  desc: 'Interiors & renovation, Gurugram',        icon: 'service'  },
  { id: 'cafe',     name: 'Chai Trunk',          desc: 'Chai, filter coffee & snacks, Bengaluru', icon: 'cafe'   },
];

export const ATLAS_BUSINESSES = Object.fromEntries(
  Object.entries(BUSINESSES).map(([id, biz]) => [id, { ...biz, isDemo: true }])
);
export const ATLAS_BUSINESS_LIST = BUSINESS_LIST.map(b => ({ ...b, isDemo: true })); 
